### ISSUE TITLE
Crash on execution 

### ISSUE THREAD

**Issue by paines** [manicmaniac/FerretExample#1]
Thanks for wrapping up an example howto use Ferret with iOS. However nowadays something must have changed and the app crashed on objc/send setRootViewController in core.clj.

Also a little suggestion for the Readme: Java is needed (of course), but anyway.

**Comment by manicmaniac** [comment]
@paines 
Thank you for reporting the issue.

> However nowadays something must have changed and the app crashed on objc/send setRootViewController in core.clj.

Honestly this repository is not intended to be a reusable Objective-C binding but just a sample code in very limited environment.
PR is always welcome but I won't actively maintain this repository for the future.

> Also a little suggestion for the Readme: Java is needed (of course), but anyway.

Thank you. I will add Java as requirement to README.

**Comment by manicmaniac** [comment]
> I will add Java as requirement to README.

Fixed in https://github.com/manicmaniac/FerretExample/pull/2
